name: Test

on:
  pull_request:
    paths-ignore:
      - '**/*.md'
      - '.github/environment/**'

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

permissions:
  id-token: write
  contents: read

jobs:
  build_test:
    runs-on: ubuntu-latest
    environment: test1
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Setup Docker Structure Test
        run: >
          curl -LO
          https://storage.googleapis.com/container-structure-test/latest/container-structure-test-linux-amd64
          && chmod +x container-structure-test-linux-amd64 && sudo mv container-structure-test-linux-amd64
          /usr/local/bin/container-structure-test

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'
          server-id: 'codeartifact'
          server-password: 'CODEARTIFACT_AUTH_TOKEN'

      - name: Configure AWS Credentials
        id: aws_auth
        uses: aws-actions/configure-aws-credentials@v4
        with:
          audience: sts.amazonaws.com
          aws-region: ${{ vars.AWS_REGION }}
          role-to-assume: ${{ vars.AWS_ROLE_ARN }}

      - name: Get CodeArtifact Repository Authentication Token
        run: |
          TOKEN=$(aws codeartifact get-authorization-token \
            --domain ${{ vars.CODEARTIFACT_DOMAIN }} \
            --domain-owner ${{ steps.aws_auth.outputs.aws-account-id }} \
            --region ${{ vars.AWS_REGION }} \
            --query authorizationToken \
            --output text)
          echo "CODEARTIFACT_AUTH_TOKEN=$TOKEN" >> "$GITHUB_ENV"

      - name: Get CodeArtifact Repository URL
        run: |
          REPO_URL=$(aws codeartifact get-repository-endpoint \
            --domain ${{ vars.CODEARTIFACT_DOMAIN }} \
            --repository ${{ vars.CODEARTIFACT_REPO }} \
            --format maven \
            --region ${{ vars.AWS_REGION }} \
            --output text)
          echo "CODEARTIFACT_REPO_URL=$REPO_URL" >> "$GITHUB_ENV"

      - name: Build with Maven
        run: mvn clean -B verify --file pom.xml

      - name: Build Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          load: true
          tags: image:${{ github.sha }}

      - name: Test Docker Image
        run: |
          container-structure-test test --image image:${{ github.sha }} --config tests/config.yaml
